#!/usr/bin/env bash
# Install nginx web server
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow "Nginx HTTP"
sudo echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
service nginx start
