#!/usr/bin/env bash
# Displays the time for 12 horus and 59 minutes.
#   Displays hours from 0 to 12
#   Displays minutes from 1 to 59
echo "Hour: 0"
minute=1
 while [ $minute -le 59 ]

do
	echo "$minute"

	(( minute++ ))
done
echo "Hour: 1"
hour=1
while [ $hour -le 9 ]

do

  echo "$hour"

  (( hour++ ))

done
