#!/usr/bin/env bash
# maing the short script
chown nginx /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
chmod 640 /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx start nginx
